version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-rec
    ports:
      - "5000:5000"   # Expose port 5000 for the Flask app
    volumes:
      - ./data:/appli/data  # Mount the host's 'data' directory to the container's '/appli/data'
      - ./logs:/appli/logs   # Mount the host's 'logs' directory to the container's '/appli/logs'
      - ./users:/appli/users   # Mount the host's 'users' directory to the container's '/appli/users'
    environment:
      FLASK_ENV: development  # Example environment variable (you can adjust this based on your app)
      SIZE: 500
    env_file:
      - mlflow_and_sp.env
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "curl", "http:localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped  # Automatically restart the container if it fails

  routes_test:
    build: 
      context: ./test_app
    container_name: app-test
    volumes:
      - ./test_app:/app
    restart: on-failure
    depends_on:
      - app
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
