data_ingestion:
  root_dir: data/raw
  source_URL: https://github.com/music_reco/tree/master/data/source/dataset.zip
  local_data_file: data/raw/dataset.zip
  unzip_dir: data/raw

data_validation:
  root_dir: data
  unzip_dir: data/raw/song_df.csv
  STATUS_FILE: data/status.txt

data_transformation:
  root_dir: data/processed
  data_path: data/raw/song_df.csv
  reco_dir: data/to_rec
  genres:
    [
      'alternative',
      'classical',
      'country',
      'edm',
      'hip-hop',
      'jazz',
      'latin',
      'pop',
      'r-n-b',
      'rock'
    ]

model_trainer:
  root_dir: models
  X_train_path: data/processed/X_train.csv
  X_test_path: data/processed/X_test.csv
  y_train_path: data/processed/y_train.csv
  y_test_path: data/processed/y_test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: metrics
  X_test_path: data/processed/X_test.csv
  y_test_path: data/processed/y_test.csv
  model_path: models/model.joblib
  metric_file_name: metrics/metrics.json

unsmodel_fit:
  root_dir: models
  features_path_prefix: data/to_rec/to_rec_
  genres_path: data/to_rec/genres.txt
  model_dir: models
  model_name_prefix: umodel_
  metrics_path_prefix: metrics/uns_metrics_
