name: CI - Dockerized API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Start Services
      run: docker-compose up --build -d

    - name: Wait for Service Healthcheck
      run: |
        echo "Waiting for app container to become healthy..."
        for i in {1..10}; do
          if [ "$(docker inspect --format='{{json .State.Health.Status}}' app-rec)" == "\"healthy\"" ]; then
            echo "App is healthy!"
            exit 0
          fi
          echo "Retrying in 10s..."
          sleep 10
        done
        echo "App failed to become healthy."
        docker logs app-rec
        exit 1

    - name: Run API Tests
      run: docker-compose run --rm routes_test

    - name: Tear Down
      if: always()
      run: docker-compose down
