name: Dockerized Flask App Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Vérification du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer Docker et Docker Compose
    - name: Set up Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Étape 3 : Construire et exécuter Docker Compose
    - name: Build and Run Docker Compose
      run: |
        docker-compose down || true  # Arrête les conteneurs existants
        docker-compose up --build --abort-on-container-exit
      continue-on-error: true

    # Étape 4 : Afficher les logs des tests
    - name: Display Test Logs
      if: always()
      run: |
        echo "======= TESTS LOG ======="
        docker logs app-test || echo "No logs available for app-test."
