name: CI - Dockerized API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Start Services
      run: docker-compose up --build -d

    - name: Wait for App to be Ready
      run: |
        echo "Waiting for app to be ready..."
        for i in {1..12}; do
          if curl -s http://localhost:5000/; then
            echo "App is ready!"
            exit 0
          fi
          echo "Retrying in 10 seconds..."
          sleep 10
        done
        echo "App did not become ready in time."
        docker logs app-rec
        exit 1

    - name: Run API Tests
      run: docker-compose run --rm routes_test

    - name: Tear Down
      if: always()
      run: docker-compose down
